export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system (Aura Professional Light & Dark M3)
        "tertiary-fixed": "#ffdcc5",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#f2effb",
        "surface": "var(--surface)",
        "primary": "var(--primary)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary": "var(--on-primary)",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-background": "var(--on-background)",
        "on-tertiary-fixed": "#301400",
        "error": "#ba1a1a",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#07006c",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container": "var(--surface-container)",
        "on-secondary-fixed-variant": "#43474b",
        "secondary": "#5a5f62",
        "surface-container-highest": "var(--surface-container-highest)",
        "outline": "var(--outline)",
        "on-secondary-fixed": "#171c1f",
        "surface-variant": "var(--surface-variant)",
        "surface-tint": "#494bd6",
        "outline-variant": "var(--outline-variant)",
        "tertiary": "#904900",
        "secondary-container": "#dce0e4",
        "secondary-fixed-dim": "#c3c7cb",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-container": "#b55d00",
        "primary-container": "var(--primary-container)",
        "surface-container-low": "var(--surface-container-low)",
        "on-surface": "var(--on-surface)",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-primary": "#c0c1ff",
        "background": "var(--background)",
        "surface-bright": "var(--surface-bright)",
        "inverse-surface": "#303038",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "var(--surface-dim)",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dfe3e7",
        "on-secondary-container": "#5e6367",
        "tertiary-fixed-dim": "#ffb783",

        // Legacy compatibility
        metro: {
          blue:   '#2563EB',
          yellow: '#EAB308',
          red:    '#EF4444',
          green:  '#22C55E',
          violet: '#8B5CF6',
          pink:   '#EC4899',
          dark:   'var(--bg-primary)',
          card:   'var(--card-bg)',
          border: 'var(--card-border)',
          accent: 'var(--accent-color)',
        },
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "lg": "24px",
        "xs": "4px",
        "xl": "32px",
        "gutter": "16px",
        "base": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "sans": ['Inter', 'system-ui', 'sans-serif'],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"]
      },
      animation: {
        'pulse-slow':  'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up':    'slideUp 0.3s ease-out',
        'fade-in':     'fadeIn 0.4s ease-out',
        'bounce-dot':  'bounceDot 1.4s infinite ease-in-out',
      },
      keyframes: {
        slideUp:   { '0%': { transform: 'translateY(20px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        fadeIn:    { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        bounceDot: { '0%, 80%, 100%': { transform: 'scale(0)' }, '40%': { transform: 'scale(1)' } },
      },
      backgroundImage: {
        'gradient-metro': 'linear-gradient(135deg, #0F1117 0%, #1A1D27 50%, #0D1321 100%)',
        'gradient-card':  'linear-gradient(145deg, #1A1D27, #12151E)',
        'gradient-blue':  'linear-gradient(135deg, #2563EB, #1D4ED8)',
        'gradient-hero':  'linear-gradient(135deg, #6366F1 0%, #8B5CF6 50%, #EC4899 100%)',
      },
    },
  },
  plugins: [],
}
